apiVersion: v1
kind: Service
metadata:
  name: "{{ template "temp-harbor-chart.portal" . }}"
  labels:
{{ include "temp-harbor-chart.labels" . | indent 4 }}
spec:
{{- if  (eq .Values.expose.ingress.controller "gce") }}
  type: NodePort
{{- end }}
  ports:
    - port: {{ template "temp-harbor-chart.portal.servicePort" . }}
      targetPort: {{ template "temp-harbor-chart.portal.containerPort" . }}
  selector:
{{ include "harbor.matchLabels" . | indent 4 }}
    component: portal
