apiVersion: v1
kind: Service
metadata:
  name: {{ template "temp-harbor-chart.core" . }}
  labels:
{{ include "temp-harbor-chart.labels" . | indent 4 }}
spec:
{{- if  (eq .Values.expose.ingress.controller "gce") }}
  type: NodePort
{{- end }}
  ports:
    - name: {{ ternary "https-web" "http-web" .Values.internalTLS.enabled }}
      port: {{ template "harbor.core.servicePort" . }}
      targetPort: {{ template "harbor.core.containerPort" . }}
  selector:
{{ include "harbor.matchLabels" . | indent 4 }}
    component: core
